# Generated by Django 6.1.1 on 2026-09-17 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('funcionario', 'Funcionário'), ('gestor', 'Gestor'), ('admin', 'Administrador')], default='funcionario', max_length=20)),
                ('gestor', models.ForeignKey(blank=True, limit_choices_to={'papel': 'gestor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='ponto.perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida_almoco', 'Saída para o almoço'), ('volta_almoco', 'Volta do almoço'), ('saida_cafe', 'Saída para o café'), ('volta_cafe', 'Volta do café'), ('saida', 'Saída')], max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pontos/%Y/%m/%d/')),
                ('registrado_manualmente', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
