# Generated by Django 6.1.1 on 2026-09-23 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_registroponto_ativo_historicoalteracaoponto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAjustePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('criacao', 'Criação'), ('exclusao', 'Exclusão')], max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('saida_almoco', 'Saída para o almoço'), ('volta_almoco', 'Volta do almoço'), ('saida_cafe', 'Saída para o café'), ('volta_cafe', 'Volta do café'), ('saida', 'Saída')], max_length=20, null=True)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('motivo_funcionario', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('gestor_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto.registroponto')),
            ],
        ),
    ]
